# Generated by Django 4.2.7 on 2023-12-03 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_fee_currency2"),
    ]

    operations = [
        migrations.AddField(
            model_name="fee",
            name="currency3",
            field=models.ForeignKey(
                blank=True,
                db_column="currency3",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cur3",
                to="main.currency",
            ),
        ),
        migrations.AlterField(
            model_name="fee",
            name="currency2",
            field=models.ForeignKey(
                blank=True,
                db_column="currency2",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cur2",
                to="main.currency",
            ),
        ),
    ]
