# Generated by Django 4.2.7 on 2023-12-03 23:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_fee_currency3_alter_fee_currency2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fee",
            name="currency2",
        ),
        migrations.RemoveField(
            model_name="fee",
            name="currency3",
        ),
    ]
